const { contactUsEmail } = require("../mail/templates/contactFormRes"); // Import the email template for the contact form response
const mailSender = require("../utils/mailSender"); // Import the mail sending utility

// Controller function for handling contact form submissions
exports.contactUsController = async (req, res) => {
  const { email, firstname, lastname, message, phoneNo, countrycode } = req.body; // Extract fields from the request body
  console.log(req.body); // Log the request body for debugging

  try {
    // Send an email using the mailSender utility
    const emailRes = await mailSender(
      email, // Recipient email
      "Your Data send successfully", // Subject of the email
      contactUsEmail(email, firstname, lastname, message, phoneNo, countrycode) // Email body generated by the contactUsEmail template
    );

    console.log("Email Res ", emailRes); // Log the email response for debugging
    return res.json({
      success: true, // Indicate successful email sending
      message: "Email sent successfully", // Success message
    });
  } catch (error) {
    console.log("Error", error); // Log the error for debugging
    console.log("Error message :", error.message); // Log the specific error message
    return res.json({
      success: false, // Indicate failure
      message: "Something went wrong...", // Error message
    });
  }
};
